- hosts: all
  become: true
  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present
  - name: copy Index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: start apache2 service
    service:
      name: apache2
      state: started
